spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values: ["pool-a"]
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-standard-wffc
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
  # (optional) fsType: ext4

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-standard-wffc-retain
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer   # create the disk in the same zone as the node that schedules the pod
reclaimPolicy: Retain                     # DON’T delete the disk when PVC is deleted
allowVolumeExpansion: true
parameters:
  type: pd-standard


livenessProbe:
  exec:
    command: ["sh", "-c", "test -d /mnt/data"]
  initialDelaySeconds: 10   # wait before first check
  periodSeconds: 15         # check every 15s
  failureThreshold: 3       # after 3 failed checks, restart pod

